# Generated by Django 5.1 on 2024-08-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfosPecas',
            fields=[
                ('idPeca', models.AutoField(primary_key=True, serialize=False)),
                ('nomePeca', models.CharField(max_length=255, unique=True)),
                ('situPeca', models.IntegerField()),
                ('fornecedorPeca', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisePeca',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('situPeca', models.IntegerField()),
                ('IdUsuario', models.IntegerField()),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('idPeca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.infospecas')),
            ],
        ),
    ]
