# Generated by Django 5.1 on 2024-09-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_analisepeca_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infospecas',
            name='nomePeca',
        ),
    ]
