# Generated by Django 5.1 on 2024-09-10 16:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_analisepeca_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospecas',
            name='nomePeca',
            field=models.CharField(default='Default Value', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='analisepeca',
            name='IdUsuario',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
