# Generated by Django 5.1 on 2024-09-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_infospecas_nomepeca_alter_analisepeca_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisepeca',
            name='idPeca',
            field=models.IntegerField(),
        ),
    ]
