# Generated by Django 5.1 on 2024-09-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_analisepeca_idpeca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisepeca',
            name='idPeca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.infospecas'),
        ),
        migrations.AlterField(
            model_name='infospecas',
            name='nomePeca',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
