# Generated by Django 5.1 on 2024-09-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_analisepeca_idpeca_alter_infospecas_nomepeca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('class_label', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.infospecas')),
            ],
        ),
    ]
